# Generated by Django 6.0.6 on 2026-07-19 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('buyer', 'Buyer'), ('reseller', 'Reseller'), ('seller', 'Seller')], default='buyer', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('account_approved', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=5, null=True)),
                ('referral_by', models.CharField(blank=True, max_length=150, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'EMAIL'), ('phone', 'PHONE'), ('sms', 'SMS')], max_length=10, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='authApp.accounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(blank=True, choices=[('managing_director', 'Managing Director'), ('order_manager', 'Order Manager'), ('stock_manager', 'Stock Manager'), ('logistic_manager', 'Logistic Manager'), ('catalog_manager', 'catalog_manager'), ('sales_manager', 'sales_manager')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authApp.userprofile')),
            ],
        ),
    ]
