# Generated by Django 6.0.6 on 2026-07-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_remove_product_price_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_per_order',
            new_name='minimum_quantity_per_order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_inStock',
            new_name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_quantityOrder',
        ),
        migrations.CreateModel(
            name='ProductQuantityOrderOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_order', models.PositiveIntegerField()),
                ('price_per_quantity_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_options', to='productApp.product')),
            ],
            options={
                'ordering': ['quantity_per_order'],
                'unique_together': {('product', 'quantity_per_order')},
            },
        ),
    ]
