# Generated by Django 6.0.6 on 2026-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_rename_quantity_per_order_product_minimum_quantity_per_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantityorderoptions',
            name='price_per_quantity_order',
        ),
        migrations.AddField(
            model_name='product',
            name='price_moq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
